include: package:very_good_analysis/very_good_analysis.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_escaping_inner_quotes: false
    avoid_redundant_argument_values: false
    avoid_relative_lib_imports: true
    avoid_web_libraries_in_flutter: false
    prefer_const_constructors_in_immutables: false
    unnecessary_const: false
    use_build_context_synchronously: false
