name: lovediary
description: "A mobile application for long distance relationships."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.0.0
  permission_handler: ^10.4.0
  firebase_core_web: ^2.0.0
  intl: ^0.20.2
  image_picker: ^0.8.7
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  geocoding: ^2.1.1
  flutter_polyline_points: ^1.0.0
  firebase_messaging: ^14.6.9 # Added firebase_messaging

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/
    - lib/l10n/

flutter_gen:
  output: lib/gen/
  line_length: 80

l10n:
  arb-dir: lib/l10n/
  output-dir: lib/gen/l10n/
  template-arb-file: app_en.arb
  preferred-supported-locales: ["en", "zh"]
