name: lovediary
description: "A mobile application for long distance relationships."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.0.0
  intl: ^0.20.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.2.0
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  geocoding: ^4.0.0
  flutter_polyline_points: ^2.1.0
  shared_preferences: ^2.2.2
  # Video/Voice calling
  agora_rtc_engine: ^6.3.2
  # Real-time messaging
  stream_chat_flutter: ^9.12.0
  # AI chatbot - using compatible version
  google_generative_ai: ^0.4.3
  # Translation - using http-based solution
  http: ^1.1.0
  # Calendar
  table_calendar: ^3.0.9
  # Gamification
  confetti: ^0.8.0
  # Additional utilities
  uuid: ^4.1.0
  url_launcher: ^6.2.1
  file_picker: ^10.2.0
  video_player: ^2.8.1
  camera: ^0.11.1
  path_provider: ^2.1.1
  connectivity_plus: ^6.1.4

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/
    - lib/l10n/

flutter_gen:
  output: lib/gen/
  line_length: 80
